config/routes.rb
Rails.application.routes.draw do
  resources :subjects do 
    member do
      get :edit_grade
      put :update_grade
    end
  end
  resources :students

  post '/enroll_student' => 'subjects#enroll'
  delete '/unenroll_student' => 'subjects#unenroll'

  root to: "students#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :student_subjects, :dependent => :destroy
	has_many :subjects, :through => :student_subjects

	validates_presence_of :name
	validates_format_of :birthday, :with => /\d{4}-\d{2}-\d{2}/
	validates_format_of :phone_number, :with => /09\d{9}/
	validates_format_of :email, :with => /[^\s@]+@[^\s@]+\.[^\s@]+/
	validates_presence_of :course
end

app/models/student_subject.rb
class StudentSubject < ActiveRecord::Base
	belongs_to :subject
	belongs_to :student

	validates_presence_of :subject_id
	validates_presence_of :student_id
	validates :grade, numericality: { less_than_or_equal_to: 100, greater_than_or_equal_to: 65 }, allow_blank: true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :student_subjects, :dependent => :destroy
	has_many :students, :through => :student_subjects

	validates_presence_of :title
	validates_presence_of :subject_code
	validates_presence_of :teacher
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  before_action :set_enrolled_subjects, only: %i[ show ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    def set_enrolled_subjects
      @enrolled_subjects = Subject.joins(:student_subjects).where(student_subjects: {student_id: params[:id]})
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :birthday, :email, :phone_number, :course)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy edit_grade update_grade]
  before_action :set_students_available, only: %i[ show enroll]
  before_action :set_enrolled_students, only: %i[ show ] 
  before_action :set_student, only: %i[ edit_grade update_grade]

  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1 or /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "Subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def enroll
    @subject = Subject.find(params[:enrollment][:subject_id])
    @student = Student.find(params[:enrollment][:student_id])
    @enrollment = StudentSubject.new
    @enrollment.subject = @subject
    @enrollment.student = @student

    respond_to do |format|
      if @enrollment.save!
        format.html { redirect_to subject_url(@subject), notice: "Student enrolled successfully." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def unenroll
    @student_subject = StudentSubject.where(student_id: params[:id], subject_id: params[:subject_id]).first
    @student_subject.destroy

    respond_to do |format|
      if params[:from_subjects] == "1"
        format.html { redirect_to subject_path(params[:subject_id]), notice: "Student unenrolled successfully." }
      else
        format.html { redirect_to student_path(params[:id]), notice: "Student unenrolled successfully." }
      end
      format.json { head :no_content }
    end
  end

  def edit_grade
  end

  def update_grade
    @record = StudentSubject.find_by_id(params[:record_id])

    respond_to do |format|
      if @record.update_attributes(grade: params[:grade])
        format.html { redirect_to subject_path(@subject), notice: "Grade updated successfully." }
      else
        format.html { render :edit_grade, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    def set_enrolled_students
      @enrolled_students = Student.select('students.*, student_subjects.grade').joins(:student_subjects).where(student_subjects: {subject_id: params[:id]})
    end

    def set_students_available
      subject_id = params[:enrollment] || params[:id]
      enrolled_students = Student.joins(:student_subjects).where(student_subjects: {subject_id: subject_id})
      @students_available = Student.where.not(id: enrolled_students.pluck(:id))
    end

    def set_student
      @student = Student.select('students.*, student_subjects.grade, student_subjects.id as record_id').joins(:student_subjects).where(student_subjects: {student_id: params[:student_id]}).first
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:title, :subject_code, :teacher)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentGradeMgmtSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Student Grade Management System</h1>
    <br>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<div class="container">
  <%= form_with(model: student, local: true) do |form| %>
    <% if student.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

        <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :student_name, placeholder: "Juan Dela Cruz" %>
    </div>

    <div style="display: flex; column-gap: 1.5rem;">
      <div style="flex-basis: 0; flex-grow: 1;" class="field">
        <%= form.label :birthday %>
        <%= form.date_field :birthday, id: :student_birthday %>
      </div>

      <div style="flex-basis: 0; flex-grow: 1;" class="field">
        <%= form.label :phone_number %>
        <%= form.text_field :phone_number, id: :student_phone_number, placeholder: "09123456789", maxlength: 11 %>
      </div>
    </div>

    <div style="display: flex; column-gap: 1.5rem;">
      <div style="flex-basis: 0; flex-grow: 1;" class="field">
        <%= form.label :email %>
        <%= form.text_field :email, id: :student_email, placeholder: "juandelacruz@email.com" %>
      </div>

      <div style="flex-basis: 0; flex-grow: 1;" class="field">
        <%= form.label :course %>
        <%= form.text_field :course, id: :student_course %>
      </div>
    </div>



    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</div>

app/views/students/_subject_enrolled_to_list.html.erb
<div class="container">
	<h2>Enrolled to: </h2>

	<table>
	  <thead>
	    <tr>
	      <th style="background-color: #d9ebf9; color: black;">Title</th>
	      <th style="background-color: #d9ebf9; color: black;">Subject code</th>
	      <th style="background-color: #d9ebf9; color: black;">Teacher</th>
	      <th style="background-color: #d9ebf9; color: black;" colspan="3">Actions</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @enrolled_subjects.each do |subject| %>
	      <tr>
	        <td><%= subject.title %></td>
	        <td><%= subject.subject_code %></td>
	        <td><%= subject.teacher %></td>
	        <td><%= link_to 'Unenroll', unenroll_student_path(id: student.id, subject_id: subject.id), method: :delete, data: { confirm: "Are you sure you want to unenroll #{student.name} to #{subject.title} ?" } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>

app/views/students/edit.html.erb
<h1>Editing Student with ID: <%=@student.id%></h1>

<%= render 'form', student: @student %>

<%= link_to '❮ Back', students_path, class: "button" %>

app/views/students/index.html.erb
<div style="display: flex; justify-content: space-between; align-items: baseline;">
  <h1>Students</h1>
  <%= link_to 'Subjects List ❯', subjects_path, class: "button" %>
</div>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthday</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Course</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.birthday %></td>
        <td><%= student.email %></td>
        <td><%= student.phone_number %></td>
        <td><%= student.course %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Delete', student, method: :delete, data: { confirm: "Are you sure you want to delete #{student.name} ?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '+ New Student', new_student_path, class: "button" %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to '❮ Back', root_path, class: "button" %>

app/views/students/show.html.erb
<h1>Student with ID: <%=@student.id%></h1>

<p id="notice"><%= notice %></p>

<div class="container">
    <div class="field">
      <%= label_tag :name %>
      <%= text_field_tag :name, @student.name, disabled: true %>
    </div>

    <div style="display: flex; column-gap: 1.5rem;">
      <div style="flex-basis: 0; flex-grow: 1;" class="field">
        <%= label_tag :birthday %>
        <%= text_field_tag :birthday, @student.birthday, disabled: true %>
      </div>

      <div style="flex-basis: 0; flex-grow: 1;" class="field">
        <%= label_tag :phone_number %>
        <%= text_field_tag :phone_number, @student.phone_number, disabled: true %>
      </div>
    </div>

    <div style="display: flex; column-gap: 1.5rem;">
      <div style="flex-basis: 0; flex-grow: 1;" class="field">
        <%= label_tag :email %>
        <%= text_field_tag :email, @student.email, disabled: true %>
      </div>

      <div style="flex-basis: 0; flex-grow: 1;" class="field">
        <%= label_tag :course %>
        <%= text_field_tag :course, @student.course, disabled: true %>
      </div>
    </div>

    <%= link_to 'Edit', edit_student_path(@student), class: 'button' %>
</div>

<br>
<%= render 'subject_enrolled_to_list', student: @student %>

<%= link_to '❮ Back', root_path, class: "button" %>

app/views/subjects/_enroll_form.html.erb
<div class="container">
    <h2>Enroll Student to <%=subject.title%> </h2>

    <%= form_tag(enroll_student_path, method: "post", local: true) do %>

    <%= hidden_field_tag "enrollment[subject_id]", subject.id %>

    <div class="field">
      <%= label_tag :name %>
      <%= select_tag "Students Available", options_from_collection_for_select(@students_available.present? ? @students_available : [], 'id', 'name'), {class: '', name: "enrollment[student_id]", disabled: @students_available.blank?}  %>
    </div>

    <%= submit_tag("Enroll", disabled: @students_available.blank?) %>
    <% end %>
</div>

app/views/subjects/_enrolled_students_list.html.erb
<div class="container">
	<h2>Currently Enrolled Students: </h2>

	<table>
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Birthday</th>
	      <th>Email</th>
	      <th>Phone number</th>
	      <th>Course</th>
	      <th>Grade</th>
	      <th colspan="3">Actions</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @enrolled_students.each do |student| %>
	      <tr>
	        <td><%= student.name %></td>
	        <td><%= student.birthday %></td>
	        <td><%= student.email %></td>
	        <td><%= student.phone_number %></td>
	        <td><%= student.course %></td>
	        <td><%= student.grade %></td>
	        <td><%= link_to 'Unenroll', unenroll_student_path(id: student.id, subject_id: subject.id, from_subjects: 1), method: :delete, data: { confirm: "Are you sure you want to unenroll #{student.name} to #{subject.title} ?" } %></td>
	        <td><%= link_to 'Edit Grade', edit_grade_subject_path(student_id: student.id) %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>

app/views/subjects/_form.html.erb
<div class="container">
  <%= form_with(model: subject, local: true) do |form| %>
    <% if subject.present? && subject.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

        <ul>
        <% subject.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :subject_title, placeholder: "Programming" %>
    </div>

    <div class="field">
      <%= form.label :subject_code %>
      <%= form.text_field :subject_code, id: :subject_subject_code, placeholder: "PROG1" %>
    </div>

    <div class="field">
      <%= form.label :teacher %>
      <%= form.text_field :teacher, id: :subject_teacher, placeholder: "Juan Dela Cruz" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</div>

app/views/subjects/edit.html.erb
<h1>Editing Subject with Code: <%=@subject.subject_code%></h1>

<%= render 'form', subject: @subject %>

<%= link_to '❮ Back', subjects_path, class: "button" %>

app/views/subjects/edit_grade.html.erb
<h1><%=@subject.title%> Grade For Student: <%=@student.name%></h1>

<div class="container">
    <%= form_tag(update_grade_subject_path, method: "put", local: true) do %>

    <% if @record.present? && @record.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@record.errors.count, "error") %> prohibited this subject from being saved:</h2>

        <ul>
        <% @record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= hidden_field_tag "record_id", @student.record_id %>
    <%= hidden_field_tag "student_id", @student.id %>

    <div class="field">
      <%= label_tag :grade %>
      <%= text_field_tag :grade, @student.grade %>
    </div>


	<%= submit_tag("Save") %>
    <% end %>
</div>

<%= link_to '❮ Back', subject_path(@subject), class: "button" %>

app/views/subjects/enroll.js.erb
alert('<%=@student_subject.errors%>');

app/views/subjects/index.html.erb
<div style="display: flex; justify-content: space-between; align-items: baseline;">
  <h1>Subjects</h1>
  <%= link_to '❮ Students List', students_path, class: "button" %>
</div>

<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th style="background-color: #d9ebf9; color: black;">Title</th>
      <th style="background-color: #d9ebf9; color: black;">Subject code</th>
      <th style="background-color: #d9ebf9; color: black;">Teacher</th>
      <th style="background-color: #d9ebf9; color: black;" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.title %></td>
        <td><%= subject.subject_code %></td>
        <td><%= subject.teacher %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: "Are you sure you want to delete #{subject.title} ?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '+ New Subject', new_subject_path, class: "button" %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to '❮ Back', subjects_path, class: "button" %>

app/views/subjects/show.html.erb
<h1>Subject with Code: <%=@subject.subject_code%></h1>

<p id="notice"><%= notice %></p>

<div class="container">
    <div class="field">
      <%= label_tag :name %>
      <%= text_field_tag :name, @subject.title, disabled: true %>
    </div>

    <div class="field">
      <%= label_tag :subject_code %>
      <%= text_field_tag :name, @subject.subject_code, disabled: true %>
    </div>

    <div class="field">
      <%= label_tag :teacher %>
      <%= text_field_tag :name, @subject.teacher, disabled: true %>
    </div>

    <%= link_to 'Edit', edit_subject_path(@subject), class: 'button' %>
</div>

<br>
<%= render 'enroll_form', subject: @subject %>

<%= render 'enrolled_students_list', subject: @subject %>

<%= link_to '❮ Back', subjects_path, class: "button" %>